//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Automobile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Automobile()
        {
            this.Customers_Inquiries = new HashSet<Customers_Inquiries>();
            this.Order_Deatils = new HashSet<Order_Deatils>();
        }
    
        public int AutomobileID { get; set; }
        public int CompanyID { get; set; }
        public string Status { get; set; }
        public int ModelID { get; set; }
        public double Price { get; set; }
    
        public virtual AutomobilesCompany AutomobilesCompany { get; set; }
        public virtual ModelDetail ModelDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Inquiries> Customers_Inquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Deatils> Order_Deatils { get; set; }
    }
}
