//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers_Inquiries
    {
        public int InquiryID { get; set; }
        public int UserID { get; set; }
        public int AutomobileID { get; set; }
        public string Message { get; set; }
    
        public virtual Automobile Automobile { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
