//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Phone
    {
        public int UserID { get; set; }
        public int Ph1 { get; set; }
        public int Ph2 { get; set; }
        public int Cell { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
